#goal definition
robot_module_msgs/JointCommand[] joints
---
#result definition
franka_tool_handover/CostVariables final_cost
bool action_completed
---
#feedback
franka_tool_handover/CostVariables cost_vars
